//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeAndRestaurant.Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CafeAndRestaurant.Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Balıklar {
            get {
                object obj = ResourceManager.GetObject("Balıklar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Balıklar1 {
            get {
                object obj = ResourceManager.GetObject("Balıklar1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] ButunUrunler {
            get {
                object obj = ResourceManager.GetObject("ButunUrunler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Çorbalar {
            get {
                object obj = ResourceManager.GetObject("Çorbalar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] FastFood {
            get {
                object obj = ResourceManager.GetObject("FastFood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] FastFood1 {
            get {
                object obj = ResourceManager.GetObject("FastFood1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] İçecekler {
            get {
                object obj = ResourceManager.GetObject("İçecekler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Kahvaltı {
            get {
                object obj = ResourceManager.GetObject("Kahvaltı", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Kahvaltı1 {
            get {
                object obj = ResourceManager.GetObject("Kahvaltı1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Mezeler {
            get {
                object obj = ResourceManager.GetObject("Mezeler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Mezeler1 {
            get {
                object obj = ResourceManager.GetObject("Mezeler1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Pastalar {
            get {
                object obj = ResourceManager.GetObject("Pastalar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Salatalar {
            get {
                object obj = ResourceManager.GetObject("Salatalar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Tatlılar {
            get {
                object obj = ResourceManager.GetObject("Tatlılar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Yemekler {
            get {
                object obj = ResourceManager.GetObject("Yemekler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static byte[] Yemekler1 {
            get {
                object obj = ResourceManager.GetObject("Yemekler1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
